### ISSUE TITLE
Some questions are too easy

### ISSUE THREAD

**Issue by jjdelvalle** [Pikamander2/japanese-characters#4]
I know you mentioned on reddit that you wanted a perfectly simple app without a lot of unnecessary features. However, this seems like something that's potentially making the app not too efficient.

Whenever a character has a dakuten or a handakuten and none of the answer have a voiced consonant but the answer, it becomes completely trivial to pick the right answer. Take this screenshot as an example:

![screenshot_2015-01-03-18-15-49](https://cloud.githubusercontent.com/assets/1283149/5609395/33022fe8-9465-11e4-86c9-95448bce30a2.png)

it's pretty trivial that `go` is the correct answer, without even knowing any of the characters.

Would you be interested in fixing this by picking out other characters with markers or are you fine with the current behaviour?

I'm asking because I was planning on making a PR, but won't bother if you don't think it's an issue.

**Comment by Pikamander2** [comment]
That's true, it does make some questions too easy. If you want to modify it so that it makes the four answers consistent (no dakuten, dakuten, handakuten), then I'll accept the pull request.

**Comment by Pikamander2** [comment]
I went ahead and messed with your changes a bit. I noticed that there were still some issues with easy questions, so I split the dakuten/handakuten into their own pool. The latest version should fix the issue completely. Thoughts?

**Comment by jjdelvalle** [comment]
Ow, commits are a bit of mess now, mine aren't congruent with yours ^^

Looks better tho! I guess this issue can be closed now. I don't see how questions would be too easy now (unless you already know Kana!)
