### ISSUE TITLE
Add a free license

### ISSUE THREAD

**Issue by pizzamaker** [Pikamander2/japanese-characters#7]
I couldn't find any licensing information. For this app to be open source, it needs to be under a free license. I recommend GPLv3 :)

**Comment by Pikamander2** [comment]
How do I add a license to it? Do I just add it as a text file, or is it a Github setting that I have to change?

**Comment by pizzamaker** [comment]
Create a LICENSE.md file and copy paste this: https://gnu.org/licenses/gpl.html

**Comment by Pikamander2** [comment]
Added.
